import type { Locale } from '@/i18n/config';

/**
 * Every string on the landing page, in the three languages the product ships.
 *
 * The switch in the nav changes the whole page at once: a worker should never
 * have to read English to find their own language. Technical terms stay in
 * English, in Latin letters, exactly as a technician says them aloud — the
 * same rule the voice tutor follows.
 */
export const LANDER_COPY = {
  en: {
    nav: ['Method', 'Study', 'Practice', 'Work'],
    signIn: 'Sign in',
    language: 'Language',
    eyebrow: 'Voice-first training for Indian shop floors',
    headA: 'The machine teaches, ',
    headItalic: 'out loud',
    headB: ', in the worker’s own language.',
    lede: 'A technician holds a button and asks in Hindi or Marathi. The answer comes back from the employer’s own procedure documents, cites the one it used, and refuses when it has none.',
    ctaPrimary: 'Enter the platform',
    ctaSecondary: 'Read the method',
    figure: 'Fig. 01 — Axial-piston pump, 9 pistons, 16 mm bore. Exploded along the shaft axis.',
    methodEyebrow: '01 — Method',
    methodHeadA: 'Grounded in ',
    methodHeadItalic: 'their',
    methodHeadB: ' procedures, not the internet’s.',
    methodLede:
      'Each employer’s documents are indexed under their own prefix and their own key. A question is answered from that set or not at all. The tutor names the document it answered from, and where a procedure is silent it says so and sends the worker to their supervisor.',
    studyEyebrow: '02 — Study',
    studyHeadA: 'Swashplate angle sets ',
    studyHeadItalic: 'everything',
    studyHeadB: ' downstream.',
    practiceEyebrow: '03 — Practice',
    practiceHead: 'What the platform will and will not do.',
    practiceLede:
      'Accounts exist only by invitation from an employer. Scores are never reported by the device that earned them. A module closes when its assessment is passed, not when a worker says so.',
    workEyebrow: '04 — Work',
    workHead: 'Trades in the catalogue.',
    closeHeadA: 'Built for the floor, ',
    closeHeadItalic: 'not the classroom',
    closeHeadB: '.',
    fineprint: 'Invite-only · Worker accounts are created by the employer · No self sign-up anywhere',
    back: 'Back to the method',
  },
  hi: {
    nav: ['तरीका', 'अध्ययन', 'नियम', 'कोर्स'],
    signIn: 'साइन इन',
    language: 'भाषा',
    eyebrow: 'भारतीय shop floor के लिए आवाज़-पहले training',
    headA: 'मशीन खुद सिखाती है, ',
    headItalic: 'बोलकर',
    headB: ', मज़दूर की अपनी भाषा में।',
    lede: 'Technician बटन दबाकर हिंदी या मराठी में पूछता है। जवाब कंपनी की अपनी procedure documents से आता है, कौन सा document इस्तेमाल हुआ वह बताता है, और न मिलने पर साफ़ मना कर देता है।',
    ctaPrimary: 'प्लेटफ़ॉर्म पर जाएँ',
    ctaSecondary: 'तरीका पढ़ें',
    figure: 'चित्र 01 — Axial-piston pump, 9 pistons, 16 mm bore. शाफ़्ट के साथ खुला हुआ।',
    methodEyebrow: '01 — तरीका',
    methodHeadA: 'जवाब ',
    methodHeadItalic: 'उनकी',
    methodHeadB: ' procedures से, इंटरनेट से नहीं।',
    methodLede:
      'हर employer के documents उनके अपने prefix और अपनी key के नीचे रखे जाते हैं। सवाल का जवाब उसी set से आता है, वरना आता ही नहीं। Tutor बताता है कि जवाब किस document से आया, और जहाँ procedure चुप है वहाँ यह कहकर supervisor के पास भेजता है।',
    studyEyebrow: '02 — अध्ययन',
    studyHeadA: 'Swashplate का कोण ',
    studyHeadItalic: 'सब कुछ',
    studyHeadB: ' तय करता है।',
    practiceEyebrow: '03 — नियम',
    practiceHead: 'प्लेटफ़ॉर्म क्या करेगा और क्या नहीं।',
    practiceLede:
      'खाता सिर्फ़ employer के invite से बनता है। Score कभी उसी device से नहीं आता जिसने test दिया। Module तभी पूरा होता है जब assessment pass हो — सिर्फ़ कहने से नहीं।',
    workEyebrow: '04 — कोर्स',
    workHead: 'Catalogue में मौजूद trades।',
    closeHeadA: 'बनाया गया shop floor के लिए, ',
    closeHeadItalic: 'क्लासरूम के लिए नहीं',
    closeHeadB: '।',
    fineprint: 'सिर्फ़ invite से · खाते employer बनाता है · कहीं भी self sign-up नहीं',
    back: 'तरीका फिर पढ़ें',
  },
  mr: {
    nav: ['पद्धत', 'अभ्यास', 'नियम', 'कोर्स'],
    signIn: 'साइन इन',
    language: 'भाषा',
    eyebrow: 'भारतीय shop floor साठी आवाज-प्रथम training',
    headA: 'मशीनच शिकवते, ',
    headItalic: 'बोलून',
    headB: ', कामगाराच्या स्वतःच्या भाषेत.',
    lede: 'Technician बटण दाबून मराठी किंवा हिंदीत विचारतो. उत्तर कंपनीच्या स्वतःच्या procedure documents मधून येते, कोणते document वापरले ते सांगते, आणि नसेल तेव्हा स्पष्ट नकार देते.',
    ctaPrimary: 'प्लॅटफॉर्मवर जा',
    ctaSecondary: 'पद्धत वाचा',
    figure: 'आकृती 01 — Axial-piston pump, 9 pistons, 16 mm bore. शाफ्टच्या बाजूने उघडलेला.',
    methodEyebrow: '01 — पद्धत',
    methodHeadA: 'उत्तर ',
    methodHeadItalic: 'त्यांच्याच',
    methodHeadB: ' procedures मधून, इंटरनेटवरून नाही.',
    methodLede:
      'प्रत्येक employer ची documents त्यांच्या स्वतःच्या prefix आणि key खाली ठेवली जातात. प्रश्नाचे उत्तर त्याच संचातून येते, नाहीतर येतच नाही. Tutor कोणत्या document मधून उत्तर दिले ते सांगतो, आणि procedure गप्प असेल तिथे तसे सांगून supervisor कडे पाठवतो.',
    studyEyebrow: '02 — अभ्यास',
    studyHeadA: 'Swashplate चा कोन ',
    studyHeadItalic: 'सर्व काही',
    studyHeadB: ' ठरवतो.',
    practiceEyebrow: '03 — नियम',
    practiceHead: 'प्लॅटफॉर्म काय करेल आणि काय करणार नाही.',
    practiceLede:
      'खाते फक्त employer च्या invite ने तयार होते. Score कधीच ते देणाऱ्या device कडून येत नाही. Assessment pass झाल्यावरच module पूर्ण होतो — नुसते सांगून नाही.',
    workEyebrow: '04 — कोर्स',
    workHead: 'Catalogue मधील trades.',
    closeHeadA: 'shop floor साठी बनवलेले, ',
    closeHeadItalic: 'वर्गखोलीसाठी नाही',
    closeHeadB: '.',
    fineprint: 'फक्त invite ने · खाती employer तयार करतो · कुठेही self sign-up नाही',
    back: 'पद्धत पुन्हा वाचा',
  },
} satisfies Record<Locale, Record<string, unknown>>;
