/**
 * The hero, in the languages this workforce actually speaks.
 *
 * Twenty-two languages for the part of the page that carries the argument.
 * The sections below the hero stay in the three languages the product's own
 * catalogue ships (English, Hindi, Marathi), because half-translated spec
 * rows read worse than English ones.
 *
 * Two rules, both borrowed from the voice tutor's own prompt:
 *  - "worker", "technician", "platform" and every technical term stay in
 *    English, in Latin letters, the way they are actually said on a floor.
 *    Nobody on a shop floor calls themselves मज़दूर.
 *  - Each language is written in its own script.
 */
export interface HeroCopy {
  label: string;
  eyebrow: string;
  headA: string;
  headItalic: string;
  headB: string;
  lede: string;
  ctaPrimary: string;
  ctaSecondary: string;
  signIn: string;
}

export const HERO_BY_LANGUAGE: Record<string, HeroCopy> = {
  en: {
    label: 'English',
    eyebrow: 'Voice-first training for Indian shop floors',
    headA: 'The machine teaches, ',
    headItalic: 'out loud',
    headB: ', in the worker’s own language.',
    lede: 'A technician holds a button and asks in their own language. The answer comes back from the employer’s own procedure documents, cites the one it used, and refuses when it has none.',
    ctaPrimary: 'Enter the platform',
    ctaSecondary: 'Read the method',
    signIn: 'Sign in',
  },
  hi: {
    label: 'हिन्दी',
    eyebrow: 'भारतीय shop floor के लिए voice-first training',
    headA: 'मशीन खुद सिखाती है, ',
    headItalic: 'बोलकर',
    headB: ', worker की अपनी भाषा में।',
    lede: 'Technician बटन दबाकर अपनी भाषा में पूछता है। जवाब company की अपनी procedure documents से आता है, कौन सा document इस्तेमाल हुआ वह बताता है, और न मिलने पर साफ़ मना कर देता है।',
    ctaPrimary: 'Platform पर जाएँ',
    ctaSecondary: 'तरीका पढ़ें',
    signIn: 'Sign in',
  },
  mr: {
    label: 'मराठी',
    eyebrow: 'भारतीय shop floor साठी voice-first training',
    headA: 'मशीनच शिकवते, ',
    headItalic: 'बोलून',
    headB: ', worker च्या स्वतःच्या भाषेत.',
    lede: 'Technician बटण दाबून स्वतःच्या भाषेत विचारतो. उत्तर company च्या स्वतःच्या procedure documents मधून येते, कोणते document वापरले ते सांगते, आणि नसेल तेव्हा स्पष्ट नकार देते.',
    ctaPrimary: 'Platform वर जा',
    ctaSecondary: 'पद्धत वाचा',
    signIn: 'Sign in',
  },
  ta: {
    label: 'தமிழ்',
    eyebrow: 'இந்திய shop floor-க்கான voice-first training',
    headA: 'மெஷினே கற்றுக் கொடுக்கும், ',
    headItalic: 'பேசி',
    headB: ', worker-இன் சொந்த மொழியில்.',
    lede: 'Technician பட்டனை அழுத்தி தன் மொழியில் கேட்கிறார். பதில் company-யின் சொந்த procedure documents-இல் இருந்தே வரும், எந்த document என்பதையும் சொல்லும், இல்லையெனில் மறுத்துவிடும்.',
    ctaPrimary: 'Platform-க்குள் செல்',
    ctaSecondary: 'முறையைப் படி',
    signIn: 'Sign in',
  },
  te: {
    label: 'తెలుగు',
    eyebrow: 'భారతీయ shop floor కోసం voice-first training',
    headA: 'మెషీనే నేర్పుతుంది, ',
    headItalic: 'మాట్లాడుతూ',
    headB: ', worker సొంత భాషలో.',
    lede: 'Technician బటన్ నొక్కి తన భాషలో అడుగుతాడు. సమాధానం company సొంత procedure documents నుండే వస్తుంది, ఏ document వాడిందో చెబుతుంది, లేకుంటే స్పష్టంగా నిరాకరిస్తుంది.',
    ctaPrimary: 'Platform లోకి వెళ్ళండి',
    ctaSecondary: 'పద్ధతి చదవండి',
    signIn: 'Sign in',
  },
  kn: {
    label: 'ಕನ್ನಡ',
    eyebrow: 'ಭಾರತೀಯ shop floor ಗಾಗಿ voice-first training',
    headA: 'ಯಂತ್ರವೇ ಕಲಿಸುತ್ತದೆ, ',
    headItalic: 'ಮಾತನಾಡಿ',
    headB: ', worker ನ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ.',
    lede: 'Technician ಬಟನ್ ಒತ್ತಿ ತನ್ನ ಭಾಷೆಯಲ್ಲಿ ಕೇಳುತ್ತಾನೆ. ಉತ್ತರ company ಯ ಸ್ವಂತ procedure documents ಇಂದಲೇ ಬರುತ್ತದೆ, ಯಾವ document ಎಂದು ಹೇಳುತ್ತದೆ, ಇಲ್ಲದಿದ್ದರೆ ನಿರಾಕರಿಸುತ್ತದೆ.',
    ctaPrimary: 'Platform ಗೆ ಹೋಗಿ',
    ctaSecondary: 'ವಿಧಾನ ಓದಿ',
    signIn: 'Sign in',
  },
  gu: {
    label: 'ગુજરાતી',
    eyebrow: 'ભારતીય shop floor માટે voice-first training',
    headA: 'મશીન જ શીખવે છે, ',
    headItalic: 'બોલીને',
    headB: ', worker ની પોતાની ભાષામાં.',
    lede: 'Technician બટન દબાવીને પોતાની ભાષામાં પૂછે છે. જવાબ company ના પોતાના procedure documents માંથી જ આવે છે, કયો document વપરાયો તે કહે છે, અને ન મળે ત્યારે સ્પષ્ટ ના પાડે છે.',
    ctaPrimary: 'Platform પર જાઓ',
    ctaSecondary: 'પદ્ધતિ વાંચો',
    signIn: 'Sign in',
  },
  bn: {
    label: 'বাংলা',
    eyebrow: 'ভারতীয় shop floor-এর জন্য voice-first training',
    headA: 'মেশিনই শেখায়, ',
    headItalic: 'মুখে বলে',
    headB: ', worker-এর নিজের ভাষায়।',
    lede: 'Technician বোতাম চেপে নিজের ভাষায় জিজ্ঞেস করেন। উত্তর আসে company-র নিজস্ব procedure documents থেকেই, কোন document ব্যবহার হয়েছে তা বলে, আর না থাকলে স্পষ্ট মানা করে।',
    ctaPrimary: 'Platform-এ যান',
    ctaSecondary: 'পদ্ধতি পড়ুন',
    signIn: 'Sign in',
  },
  pa: {
    label: 'ਪੰਜਾਬੀ',
    eyebrow: 'ਭਾਰਤੀ shop floor ਲਈ voice-first training',
    headA: 'ਮਸ਼ੀਨ ਹੀ ਸਿਖਾਉਂਦੀ ਹੈ, ',
    headItalic: 'ਬੋਲ ਕੇ',
    headB: ', worker ਦੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ।',
    lede: 'Technician ਬਟਨ ਦਬਾ ਕੇ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਪੁੱਛਦਾ ਹੈ। ਜਵਾਬ company ਦੇ ਆਪਣੇ procedure documents ਤੋਂ ਹੀ ਆਉਂਦਾ ਹੈ, ਕਿਹੜਾ document ਵਰਤਿਆ ਦੱਸਦਾ ਹੈ, ਤੇ ਨਾ ਹੋਵੇ ਤਾਂ ਸਾਫ਼ ਨਾਂਹ ਕਰ ਦਿੰਦਾ ਹੈ।',
    ctaPrimary: 'Platform ਤੇ ਜਾਓ',
    ctaSecondary: 'ਤਰੀਕਾ ਪੜ੍ਹੋ',
    signIn: 'Sign in',
  },
  ml: {
    label: 'മലയാളം',
    eyebrow: 'ഇന്ത്യൻ shop floor-നായി voice-first training',
    headA: 'മെഷീൻ തന്നെ പഠിപ്പിക്കുന്നു, ',
    headItalic: 'പറഞ്ഞുകൊണ്ട്',
    headB: ', worker-ന്റെ സ്വന്തം ഭാഷയിൽ.',
    lede: 'Technician ബട്ടൺ അമർത്തി സ്വന്തം ഭാഷയിൽ ചോദിക്കുന്നു. ഉത്തരം company-യുടെ സ്വന്തം procedure documents-ൽ നിന്നുതന്നെ വരും, ഏത് document എന്ന് പറയും, ഇല്ലെങ്കിൽ വ്യക്തമായി നിരസിക്കും.',
    ctaPrimary: 'Platform-ലേക്ക് പോകുക',
    ctaSecondary: 'രീതി വായിക്കുക',
    signIn: 'Sign in',
  },
  or: {
    label: 'ଓଡ଼ିଆ',
    eyebrow: 'ଭାରତୀୟ shop floor ପାଇଁ voice-first training',
    headA: 'ମେସିନ ନିଜେ ଶିଖାଏ, ',
    headItalic: 'କହି କହି',
    headB: ', worker ର ନିଜ ଭାଷାରେ।',
    lede: 'Technician ବଟନ ଦବାଇ ନିଜ ଭାଷାରେ ପଚାରନ୍ତି। ଉତ୍ତର company ର ନିଜସ୍ୱ procedure documents ରୁ ଆସେ, କେଉଁ document ବ୍ୟବହାର ହେଲା କହେ, ନଥିଲେ ସ୍ପଷ୍ଟ ମନା କରେ।',
    ctaPrimary: 'Platform କୁ ଯାଆନ୍ତୁ',
    ctaSecondary: 'ପଦ୍ଧତି ପଢ଼ନ୍ତୁ',
    signIn: 'Sign in',
  },
  as: {
    label: 'অসমীয়া',
    eyebrow: 'ভাৰতীয় shop floor-ৰ বাবে voice-first training',
    headA: 'মেচিনেই শিকায়, ',
    headItalic: 'কথা কৈ',
    headB: ', worker-ৰ নিজৰ ভাষাত।',
    lede: 'Technician বুটাম টিপি নিজৰ ভাষাত সোধে। উত্তৰ company-ৰ নিজৰ procedure documents-ৰ পৰাই আহে, কোনটো document ব্যৱহাৰ হ’ল কয়, আৰু নাথাকিলে স্পষ্টকৈ অসন্মতি জনায়।',
    ctaPrimary: 'Platform-লৈ যাওক',
    ctaSecondary: 'পদ্ধতি পঢ়ক',
    signIn: 'Sign in',
  },
  ur: {
    label: 'اردو',
    eyebrow: 'انڈین shop floor کے لیے voice-first training',
    headA: 'مشین خود سکھاتی ہے، ',
    headItalic: 'بول کر',
    headB: '، worker کی اپنی زبان میں۔',
    lede: 'Technician بٹن دبا کر اپنی زبان میں پوچھتا ہے۔ جواب company کی اپنی procedure documents سے آتا ہے، کون سا document استعمال ہوا وہ بتاتا ہے، اور نہ ملنے پر صاف انکار کر دیتا ہے۔',
    ctaPrimary: 'Platform پر جائیں',
    ctaSecondary: 'طریقہ پڑھیں',
    signIn: 'Sign in',
  },
  bho: {
    label: 'भोजपुरी',
    eyebrow: 'भारतीय shop floor खातिर voice-first training',
    headA: 'मशीने सिखावेले, ',
    headItalic: 'बोल के',
    headB: ', worker के आपन भाषा में।',
    lede: 'Technician बटन दबा के आपन भाषा में पूछेला। जवाब company के आपन procedure documents से आवेला, कवन document इस्तेमाल भइल बतावेला, आ ना मिले त साफ मना कर देला।',
    ctaPrimary: 'Platform पर जाईं',
    ctaSecondary: 'तरीका पढ़ीं',
    signIn: 'Sign in',
  },
  mai: {
    label: 'मैथिली',
    eyebrow: 'भारतीय shop floor लेल voice-first training',
    headA: 'मशीने सिखबैत अछि, ',
    headItalic: 'बाजि कऽ',
    headB: ', worker केर अपन भाषा मे।',
    lede: 'Technician बटन दाबि कऽ अपन भाषा मे पुछैत छथि। उत्तर company केर अपन procedure documents सँ अबैत अछि, कोन document प्रयोग भेल से कहैत अछि, आ नहि रहला पर साफ मना कऽ दैत अछि।',
    ctaPrimary: 'Platform पर जाउ',
    ctaSecondary: 'तरीका पढ़ू',
    signIn: 'Sign in',
  },
  raj: {
    label: 'मारवाड़ी',
    eyebrow: 'भारतीय shop floor वास्ते voice-first training',
    headA: 'मशीन ई सिखावै, ',
    headItalic: 'बोल’र',
    headB: ', worker री अपणी भाषा में।',
    lede: 'Technician बटन दबा’र अपणी भाषा में पूछै। जवाब company रा अपणा procedure documents सूं ई आवै, कुण सो document काम आयो बतावै, अर कोनी मिलै तो साफ मना कर देवै।',
    ctaPrimary: 'Platform पर जावो',
    ctaSecondary: 'तरीको पढ़ो',
    signIn: 'Sign in',
  },
  kok: {
    label: 'कोंकणी',
    eyebrow: 'भारतीय shop floor खातीर voice-first training',
    headA: 'मशीनच शिकयता, ',
    headItalic: 'उलोवन',
    headB: ', worker च्या आपल्या भाशेन.',
    lede: 'Technician बटण दामून आपल्या भाशेन विचारता. जाप company च्या आपल्या procedure documents थावन येता, खंयचें document वापरलें तें सांगता, आनी ना जाल्यार स्पश्ट ना म्हणटा.',
    ctaPrimary: 'Platform वयर वच',
    ctaSecondary: 'पद्धत वाच',
    signIn: 'Sign in',
  },
  ne: {
    label: 'नेपाली',
    eyebrow: 'भारतीय shop floor का लागि voice-first training',
    headA: 'मेसिन आफैँ सिकाउँछ, ',
    headItalic: 'बोलेर',
    headB: ', worker कै आफ्नो भाषामा।',
    lede: 'Technician बटन थिचेर आफ्नै भाषामा सोध्छ। जवाफ company कै आफ्नो procedure documents बाट आउँछ, कुन document प्रयोग भयो भन्छ, र नभए स्पष्ट अस्वीकार गर्छ।',
    ctaPrimary: 'Platform मा जानुहोस्',
    ctaSecondary: 'तरिका पढ्नुहोस्',
    signIn: 'Sign in',
  },
  doi: {
    label: 'डोगरी',
    eyebrow: 'भारतीय shop floor आस्तै voice-first training',
    headA: 'मशीन आपूं सखांदी ऐ, ',
    headItalic: 'बोली के',
    headB: ', worker दी अपनी भाशा च।',
    lede: 'Technician बटन दबाई के अपनी भाशा च पुच्छदा ऐ। जवाब company दे अपने procedure documents थमां ई औंदा ऐ, कुस document दा इस्तेमाल होया दस्सदा ऐ, ते नेईं मिलै तां साफ़ नां करी दिंदा ऐ।',
    ctaPrimary: 'Platform पर जाओ',
    ctaSecondary: 'तरीका पढ़ो',
    signIn: 'Sign in',
  },
  ks: {
    label: 'کٲشُر',
    eyebrow: 'ہِندوستٲنی shop floor خٲطرٕ voice-first training',
    headA: 'مشین چھِ پانہٕ ہیچھناوان، ',
    headItalic: 'بۆزِتھ',
    headB: '، worker سٕنٛز پننہٕ زبانِ منٛز۔',
    lede: 'Technician چھُ بٹن دبِتھ پننہٕ زبانِ منٛز پرژھان۔ جواب چھُ company سٕنٛدِ پننہٕ procedure documents پؠٹھٕ یِوان، کُس document اِستعمال کۆر سُہ چھُ ونان، تہٕ نہٕ ملہِ تہ چھُ صاف انکار کران۔',
    ctaPrimary: 'Platform پؠٹھ گژھِو',
    ctaSecondary: 'طریقہٕ پرِو',
    signIn: 'Sign in',
  },
  sat: {
    label: 'ᱥᱟᱱᱛᱟᱲᱤ',
    eyebrow: 'ᱦᱤᱱᱫᱩᱥᱛᱟᱱ shop floor ᱞᱟᱹᱜᱤᱫ voice-first training',
    headA: 'ᱢᱮᱥᱤᱱ ᱜᱮ ᱪᱮᱫᱚᱜᱼᱟ, ',
    headItalic: 'ᱨᱚᱲ ᱠᱟᱛᱮ',
    headB: ', worker ᱟᱜ ᱱᱤᱡᱟᱹᱠ ᱯᱟᱹᱨᱥᱤ ᱛᱮ᱾',
    lede: 'Technician ᱫᱚ ᱵᱚᱴᱚᱱ ᱚᱛᱟᱭ ᱠᱟᱛᱮ ᱟᱡ ᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱠᱩᱠᱞᱤᱭᱟᱭ᱾ ᱛᱮᱞᱟ ᱫᱚ company ᱟᱜ ᱱᱤᱡᱟᱹᱠ procedure documents ᱠᱷᱚᱱ ᱜᱮ ᱦᱮᱡᱚᱜᱼᱟ, ᱚᱠᱟ document ᱵᱮᱵᱷᱟᱨ ᱦᱩᱭᱮᱱᱟ ᱚᱱᱟ ᱦᱩᱭ ᱞᱟᱹᱜᱤᱫᱟᱭ, ᱟᱨ ᱵᱟᱝ ᱧᱟᱢ ᱠᱷᱟᱱ ᱥᱟᱯᱷᱟ ᱵᱟᱝ ᱢᱮᱛᱟᱣᱟᱭ᱾',
    ctaPrimary: 'Platform ᱛᱮ ᱪᱟᱞᱟᱜ ᱢᱮ',
    ctaSecondary: 'ᱛᱚᱨᱤᱠᱟ ᱯᱟᱲᱦᱟᱣ ᱢᱮ',
    signIn: 'Sign in',
  },
  brx: {
    label: 'बर’',
    eyebrow: 'भारतनि shop floor नि थाखाय voice-first training',
    headA: 'मेसिननो सोलोंहोयो, ',
    headItalic: 'बुंनानै',
    headB: ', worker नि गावनि रावाव।',
    lede: 'Technician आ बुथाम बुथिनानै गावनि रावाव सोंयो। फिननाया company नि गावनि procedure documents निफ्राय फैयो, बबे document बाहायबाय बुंयो, आरो गैयाब्ला गोब्राब नङा बुंयो।',
    ctaPrimary: 'Platform आव थां',
    ctaSecondary: 'खान्थि फराय',
    signIn: 'Sign in',
  },
  sd: {
    label: 'سنڌي',
    eyebrow: 'انڊين shop floor لاءِ voice-first training',
    headA: 'مشين پاڻ سيکاري ٿي، ',
    headItalic: 'ڳالهائي',
    headB: '، worker جي پنهنجي ٻوليءَ ۾.',
    lede: 'Technician بٽڻ دٻائي پنهنجي ٻوليءَ ۾ پڇي ٿو. جواب company جي پنهنجن procedure documents مان ئي اچي ٿو، ڪهڙو document ڪم آيو سو ٻڌائي ٿو، ۽ نه ملڻ تي صاف انڪار ڪري ٿو.',
    ctaPrimary: 'Platform تي وڃو',
    ctaSecondary: 'طريقو پڙهو',
    signIn: 'Sign in',
  },
  bgc: {
    label: 'हरियाणवी',
    eyebrow: 'भारतीय shop floor खातर voice-first training',
    headA: 'मशीन ए सिखावै सै, ',
    headItalic: 'बोल के',
    headB: ', worker की अपणी भाषा म्ह।',
    lede: 'Technician बटन दबा के अपणी भाषा म्ह पूछै सै। जवाब company के अपणे procedure documents तै ए आवै सै, कौण सा document काम आया बतावै सै, अर ना मिलै तो साफ मना कर दे सै।',
    ctaPrimary: 'Platform पै जाओ',
    ctaSecondary: 'तरीका पढ़ो',
    signIn: 'Sign in',
  },
  hne: {
    label: 'छत्तीसगढ़ी',
    eyebrow: 'भारतीय shop floor बर voice-first training',
    headA: 'मशीने सिखाथे, ',
    headItalic: 'बोल के',
    headB: ', worker के अपन भाखा म।',
    lede: 'Technician बटन दबा के अपन भाखा म पूछथे। जवाब company के अपन procedure documents ले आथे, कोन document बउरे गइस बताथे, अउ नइ मिलय त साफ मना कर देथे।',
    ctaPrimary: 'Platform म जावव',
    ctaSecondary: 'तरीका पढ़व',
    signIn: 'Sign in',
  },
  mni: {
    label: 'ꯃꯤꯇꯩꯂꯣꯟ',
    eyebrow: 'ꯏꯟꯗꯤꯌꯥꯒꯤ shop floor ꯒꯤꯗꯃꯛ voice-first training',
    headA: 'ꯃꯆꯤꯟꯅ ꯃꯁꯥꯃꯛ ꯇꯃꯍꯩ, ',
    headItalic: 'ꯋꯥ ꯍꯥꯏꯗꯨꯅꯥ',
    headB: ', worker ꯀꯤ ꯃꯁꯥꯒꯤ ꯂꯣꯟꯗ.',
    lede: 'Technician ꯅ ꯕꯇꯟ ꯅꯝꯗꯨꯅꯥ ꯃꯁꯥꯒꯤ ꯂꯣꯟꯗ ꯍꯪꯏ. ꯄꯥꯎꯈꯨꯝ ꯑꯗꯨ company ꯒꯤ ꯃꯁꯥꯒꯤ procedure documents ꯗꯒꯤ ꯂꯥꯛꯏ, ꯀꯗꯥꯏ document ꯁꯤꯖꯤꯟꯅꯈꯤꯕꯒꯦ ꯍꯥꯏꯕꯁꯤ ꯇꯥꯀꯏ, ꯑꯃꯁꯨꯡ ꯂꯩꯇꯕ ꯃꯇꯃꯗ ꯌꯥꯗꯦ ꯍꯥꯏꯏ.',
    ctaPrimary: 'Platform ꯗ ꯆꯪꯉꯨ',
    ctaSecondary: 'ꯃꯑꯣꯡ ꯄꯥꯎ',
    signIn: 'Sign in',
  },
};

/** The order they appear in the switch: the three the product ships, then the rest. */
export const HERO_LANGUAGE_ORDER = Object.keys(HERO_BY_LANGUAGE);
